config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
  get "/articles", to: "articles#index"
  get "/articles/:id", to: "articles#show"
  post 'articles/search', to: 'articles#search'
  get "/analytics", to: "analytics#index"
end

app/models/analytic.rb
class Analytic < ApplicationRecord
  require 'fuzzystringmatch'
  validates :query, presence: true, length: { minimum: 2, maximum: 40 }
  validates :session_id, presence: true

  def searched_query(search)
    fuzzy_match = FuzzyStringMatch::JaroWinkler.create(:native)
    query_match = fuzzy_match.getDistance(search, query)
    query_match > 0.7
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :body, presence: true, length: { minimum: 20, maximum: 300 }

  # Display similar queries

  def self.search_article(query)
    where('title LIKE ?', "%#{query}%").pluck(:title, :id).first(10) if exists?
  end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def query_list
    Analytic.group(:query).pluck('query, count(query) as COUNTER')
  end

  def sort_query_list
    query_list.sort_by { |element| element[1] }.reverse.first(15)
  end

  def index
    @user_search_list = sort_query_list
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :session_present, only: [:search]

  def index
    @articles = []
  end

  def show
    @article = Article.find(params[:id])
  end

  def search
    if params[:query].empty?
      render(partial: '/shared/homepage', locals: { articles: [] })
    else
      articles = Article.search_article(params[:query])
      render(partial: '/shared/homepage', locals: { articles: articles })
      query_save(params[:query], session[:user_id])
    end
  end

  protected

  # save valid new query and replace incomplete query with a complete one

  def query_save(query, session)
    return if query.length <= 2 || query.nil?

    new_query = Analytic.new(query: query)
    new_query.session_id = session
    session_last_query = Analytic.where(session_id: session).last

    if session_last_query.nil? || !session_last_query.searched_query(query)
      new_query.save
    elsif session_last_query.query.length < query.length
      session_last_query.update(query: query)
    end
  end

  def session_present
    session[:user_id] = SecureRandom.urlsafe_base64(12) if session[:user_id].nil?
  end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/analytics/index.html.erb
<div class='container'>
  <div class="text-center">
    <button type="button" class="btn btn-success btn-lg homepage">
      <%= link_to 'Go to Homepage', root_path, {:style=>'color:#FFFFFF;'} %>
    </button>
  </div>

  <h1 class='text-center table-title'> Most Common Queries </h1>
  <table class="table table-hover analytics-table">
    <thead class="table-head">
      <tr>
        <td>Query</td>
        <td>Search Frequency</td>
      <tr>
    </thead>
    <tbody>
      <% @user_search_list.each_with_index do |analytics, index| %>
        <tr>
          <td> <%= analytics[0]  %> </td>
          <td> <%= analytics[1] %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/articles/index.html.erb
<div class='headline-section text-center'>
  <div>
    <button type="button" class="btn btn-info btn-lg analytics-button">
      <%= link_to 'See Search Analytics', analytics_path, {:style=>'color:#FFFFFF;'} %>
    </button>
  </div>
  <div>
    <%= image_tag  "search-heading.png", height: 100, class: "heading-img" %>
  </div>
  <%= render partial: '/shared/homepage', locals: { articles: @articles } %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="text-center">
    <button type="button" class="btn btn-success btn-lg homepage">
      <%= link_to 'Go to Homepage', root_path, {:style=>'color:#FFFFFF;'} %>
    </button>
  </div>
  <div class="card">
    <div class="card-body article">
      <h3 class="card-title"><%= @article.title %></h3>
      <p class="card-text text-justify"><%= @article.body  %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search Articles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<div class='form-container'>
  <%= form_with url: articles_search_path, authenticity_token: false, method: :post, data: { controller: "search", search_target: "form", turbo_frame: "articles" } do |form| %>
    <%= image_tag "search-icon.jpg", class: "search-icon" %>
    <%= form.text_field :query,
      placeholder: "Enter your query ....",
      autocomplete: "off",
      id: "search-form",
      data: { action: "input->search#querySearch" }
    %>
  <% end %>
</div>

app/views/shared/_homepage.html.erb
<div class='container'>
  <%= render partial: '/shared/form' %>

  <%= turbo_frame_tag "articles" do %>
    <% if !articles.empty? %>
      <div>
        <% articles.each do |article| %>
          <ul class="search-list">
            <li class= "list-item text-left">
              <a href='/articles/<%= article[1]%>'>
                <%= image_tag "search-icon.jpg", class: "list-icon" %>
                <%= article[0] %>
              </a>
            </li>
          </ul>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>